language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- ./Travis/installUnity.sh
script:
- ./Travis/createProject.sh
- ./Travis/installSDK.sh
- travis_wait 15 ./Travis/runTests.sh
- ./Travis/build.sh
